name: JMeterDSL Runner

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Config JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Test Runner
      run: mvn clean test

    - name: JUnit Report
      uses: actions/upload-artifact@v2
      with:
        name: junit-reports
        path: target/surefire-reports
