name: JMeterDSL Runner

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Config JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Test Runner
      run: mvn clean test

    - name: JUnit Report
      uses: actions/upload-artifact@v4
      with:
        name: junit-reports
        path: target/surefire-reports

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: "target/surefire-reports/TEST-*.xml"
